"area:frontend":
  - any: ['frontend/**']
  - all: ['!frontend/jest.config.js']

"area:backend":
  - any: ['server/**']
  - all: ['!server/jest.config.js']

"area:database":
  - "server/database/**"
  - server/knexfile.js

"area:api":
  - "server/routes/**"
  - "server/controllers/**"
  - "server/services/**"

"area:test":
  - "server/**/*.test.js"
  - jest.config.js
  - frontend/jest.config.js
  - server/jest.config.js
