name: frontend

on:
  push:
    paths: "frontend/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node: [10, 12]
        os: [ubuntu-18.04, ubuntu-20.04]

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Yarn install
        run: yarn install

      - name: Build Vue app
        run: npm run frontend:build

      - name: Validate Vue build
        run: ls frontend/dist
